config/routes.rb
Rails.application.routes.draw do

  root 'say#welcome'

  get  '/input' => 'say#form',       as: 'say_form'
  post '/speak' => 'say#say_things', as: 'speak'

end

app/models/speech.rb
class Speech < ActiveRecord::Base
  def perform!
    system "say", words
  end
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def welcome
    @recent_speeches = Speech.last 3
    render :home
  end

  def form
    # render :form
  end

  def say_things
    s = Speech.create! words: params[:words]
    s.perform!
    #flash[:notice] = "Said '#{params[:words]}. Again?"
    # redirect_to :back
    redirect_to say_form_path, notice: "Said '#{s.words}'. Again?"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsOne</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1><%= link_to "Welcome to the site", root_path %></h1>

<p><%= notice %></p>

<%= yield %>

</body>
</html>

app/views/say/form.html.erb
<p>What should I say?</p>

<form method="POST" action="<%= speak_path %>">
  <input type="text" name="words">
  <button>Speak!</button>
</form>

app/views/say/home.html.erb
<p>Welcome to the Say Server</p>
<p>It should be obvious how this works</p>
<!-- <a href="<%= say_form_path %>">Try it out!</a> -->
<%= link_to "Try it out!", say_form_path, class: "css-class" %>

<ul>
  <% @recent_speeches.each do |s| %>
    <li>
      <form method="POST" action="<%= speak_path %>">
        <input type="hidden" name="words" value="<%= s.words %>">
        <button><%= s.words %></button>
      </form>
    </li>
  <% end %>
</ul>